# Generated by Django 5.2.8 on 2025-04-22 10:00

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountMovement",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "movement_type",
                    models.SmallIntegerField(
                        choices=[(1, "Transfer from SAFE to DRAWER"), (2, "Transfer from DRAWER to SAFE")],
                        default=1,
                        verbose_name="movement type",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="amount")),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=7, verbose_name="final amount in safe"
                    ),
                ),
                ("explanation", models.TextField(blank=True, default="", verbose_name="explanation")),
                (
                    "movement_date",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="movement date"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DistributionAccountDetail",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(default=django.utils.timezone.now, verbose_name="distribution date")),
                (
                    "expected_initial_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=7, verbose_name="expected initial amount"
                    ),
                ),
                (
                    "initial_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="initial amount"),
                ),
                (
                    "member_consumed_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=7, verbose_name="member consumed amount"
                    ),
                ),
                (
                    "total_member_payment_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=7, verbose_name="total member payment amount"
                    ),
                ),
                (
                    "debt_balance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="debt balance amount"),
                ),
                (
                    "quarterly_fee_collected_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=7, verbose_name="collected fee amount"
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="final amount"),
                ),
                (
                    "expected_final_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=7, verbose_name="expected final amount"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="notes")),
            ],
        ),
        migrations.CreateModel(
            name="DistributionDate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("distribution_date", models.DateField(verbose_name="distribution date")),
                ("canceled", models.BooleanField(verbose_name="canceled")),
            ],
            options={
                "verbose_name": "distribution date",
                "verbose_name_plural": "distribution dates",
            },
        ),
        migrations.CreateModel(
            name="EmailList",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                ("description", models.TextField(blank=True, default="", verbose_name="description")),
                ("email_addresses", models.TextField(blank=True, default="", verbose_name="email addresses")),
                ("cc_task_reminders", models.BooleanField(default=False, verbose_name="cc task reminders")),
                ("cc_incidents", models.BooleanField(default=False, verbose_name="cc incidents")),
            ],
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email_code",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Member: Offer Created"),
                            (2, "Member: Saturday Reminder"),
                            (3, "Member: Order Sent to Producers"),
                            (4, "Member: Account Created"),
                            (5, "Member: Distribution Task Reminder"),
                            (101, "Producer: Total Order"),
                            (102, "Producer: No Order This Week"),
                            (103, "Producer: Product Ratings"),
                        ],
                        default="ca",
                        verbose_name="email code",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("tr", "Turkish"), ("ca", "Catala"), ("es", "Castellano"), ("en", "English")],
                        default="ca",
                        max_length=2,
                        verbose_name="language code",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="<em>(Without [BroquilGotic])</em>",
                        max_length=70,
                        verbose_name="subject",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="<em>(Do not remove the [[CONTENT]] parts.)</em>",
                        verbose_name="body",
                    ),
                ),
            ],
            options={
                "verbose_name": "email template",
                "verbose_name_plural": "email templates",
            },
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=50, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=50, null=True, verbose_name="last name")),
                ("company_name", models.CharField(blank=True, max_length=50, null=True, verbose_name="company name")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("send_ratings", models.BooleanField(default=False, verbose_name="send ratings")),
                (
                    "order_day",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=0,
                        verbose_name="order day",
                    ),
                ),
                (
                    "order_hour",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(23),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="order hour",
                    ),
                ),
                (
                    "minimum_order",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="minimum order"
                    ),
                ),
                ("fixed_products", models.BooleanField(default=False, verbose_name="fixed products")),
                ("limited_availability", models.BooleanField(default=False, verbose_name="limited availability")),
                (
                    "excel_format",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Standard"),
                            (1, "Cal Rosset"),
                            (2, "Can Pipirimosca"),
                            (3, "La Selvatana"),
                            (4, "Can Perol"),
                        ],
                        default=0,
                        verbose_name="excel format",
                    ),
                ),
                (
                    "default_category_name",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="default category name"),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="<em>(Disable the producer by clearing this option.)</em>",
                        verbose_name="active",
                    ),
                ),
                (
                    "transportation_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="transportation cost"),
                ),
                (
                    "short_product_explanation",
                    models.CharField(
                        default="",
                        help_text="<em>(Will be shown on the 'offer created' emails.)</em>",
                        max_length=80,
                        verbose_name="short product explanation",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="<em>(Long explanation about the producer. If you want to place photos or links to files, a) place them in Google Drive and create public link, b) find their public link from some other website)</em>",
                        verbose_name="description",
                    ),
                ),
            ],
            options={
                "verbose_name": "producer",
                "verbose_name_plural": "producers",
            },
        ),
        migrations.CreateModel(
            name="InactiveUser",
            fields=[],
            options={
                "verbose_name": "usuari (inactiu)",
                "verbose_name_plural": "usuaris (inactius)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="SystemUser",
            fields=[],
            options={
                "verbose_name": "usuari (sistema)",
                "verbose_name_plural": "usuaris (sistema)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="DistributionTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("distribution_date", models.DateField(verbose_name="distribution date")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ExtraInfo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "secondary_email",
                    models.EmailField(blank=True, default="", max_length=254, verbose_name="secondary email"),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="phone")),
                (
                    "secondary_phone",
                    models.CharField(blank=True, default="", max_length=15, verbose_name="secondary phone"),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date")),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="quantity")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Debt",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="quantity")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="elbroquil.payment")),
            ],
        ),
        migrations.CreateModel(
            name="Consumption",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="quantity")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="elbroquil.payment")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "visible_name",
                    models.CharField(
                        blank=True,
                        help_text="<em>(To display shorter/better names for producer categories.)</em>",
                        max_length=100,
                        null=True,
                        verbose_name="visible name",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="<em>(To change the order of appearance of categories.)</em>",
                        verbose_name="sort order",
                    ),
                ),
                ("archived", models.BooleanField(default=False, verbose_name="archived")),
                ("producer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="elbroquil.producer")),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="ProducerAvailableDate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("available_date", models.DateField(verbose_name="available date")),
                ("producer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="elbroquil.producer")),
            ],
            options={
                "verbose_name": "available date",
                "verbose_name_plural": "available dates",
            },
        ),
        migrations.CreateModel(
            name="ProducerPayment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(default=django.utils.timezone.now, verbose_name="distribution date")),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="quantity")),
                ("producer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="elbroquil.producer")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="product")),
                ("origin", models.CharField(blank=True, max_length=100, null=True, verbose_name="origin")),
                ("comments", models.CharField(blank=True, max_length=100, null=True, verbose_name="comments")),
                ("price", models.DecimalField(decimal_places=4, max_digits=9, verbose_name="price")),
                (
                    "unit",
                    models.CharField(
                        help_text="<em>(without the &euro; sign or / character.)</em>",
                        max_length=20,
                        verbose_name="unit",
                    ),
                ),
                ("integer_demand", models.BooleanField(default=False, verbose_name="integer demand")),
                (
                    "distribution_date",
                    models.DateField(
                        blank=True,
                        help_text="<em>(Only fill for products that are offered just once.)</em>",
                        null=True,
                        verbose_name="distribution date",
                    ),
                ),
                ("archived", models.BooleanField(default=False, verbose_name="archived")),
                (
                    "total_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="total quantity"),
                ),
                (
                    "arrived_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="arrived quantity"),
                ),
                (
                    "order_limit_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="<em>(Only fill for products that are offered just once.)</em>",
                        null=True,
                        verbose_name="order limit date",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name="average rating"),
                ),
                (
                    "new_product",
                    models.BooleanField(
                        default=False,
                        help_text="<em>(To highlight this product as NEW in the order pages.)</em>",
                        verbose_name="new product",
                    ),
                ),
                ("sent_to_producer", models.BooleanField(default=False, verbose_name="sent to producer")),
                ("stock_product", models.BooleanField(default=False, verbose_name="stock product")),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="elbroquil.category")),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=7, verbose_name="quantity")),
                ("rating", models.SmallIntegerField(blank=True, default=None, null=True, verbose_name="rating")),
                ("archived", models.BooleanField(default=False, verbose_name="archived")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Normal"), (10, "Did not arrive"), (20, "Min. order not met")],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "arrived_quantity",
                    models.DecimalField(decimal_places=2, max_digits=7, verbose_name="arrived quantity"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="elbroquil.product")),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
            },
        ),
        migrations.CreateModel(
            name="Quarterly",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.SmallIntegerField(verbose_name="year")),
                ("quarter", models.SmallIntegerField(verbose_name="quarter")),
                ("created_date", models.DateTimeField(default=django.utils.timezone.now, verbose_name="created date")),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="quantity")),
                (
                    "payment",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="elbroquil.payment"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
